/**
 * The errors for the QHSenseTrack objects.
 */

import {
    CHROME_EXTENSION_GENERIC_ERROR,
    CHROME_EXTENSION_INSTALLATION_ERROR,
    CHROME_EXTENSION_USER_GESTURE_REQUIRED,
    CHROME_EXTENSION_USER_CANCELED,
    CONSTRAINT_FAILED,
    ELECTRON_DESKTOP_PICKER_ERROR,
    ELECTRON_DESKTOP_PICKER_NOT_FOUND,
    FIREFOX_EXTENSION_NEEDED,
    GENERAL,
    NOT_FOUND,
    PERMISSION_DENIED,
    TRACK_IS_DISPOSED,
    TRACK_NO_STREAM_FOUND,
    UNSUPPORTED_RESOLUTION,
} from 'lib-jitsi-meet/JitsiTrackErrors'

//some const

export {
    CHROME_EXTENSION_GENERIC_ERROR,
    CHROME_EXTENSION_INSTALLATION_ERROR,
    CHROME_EXTENSION_USER_GESTURE_REQUIRED,
    CHROME_EXTENSION_USER_CANCELED,
    CONSTRAINT_FAILED,
    ELECTRON_DESKTOP_PICKER_ERROR,
    ELECTRON_DESKTOP_PICKER_NOT_FOUND,
    FIREFOX_EXTENSION_NEEDED,
    GENERAL,
    NOT_FOUND,
    PERMISSION_DENIED,
    TRACK_IS_DISPOSED,
    TRACK_NO_STREAM_FOUND,
    UNSUPPORTED_RESOLUTION,
    //some const
}
